version: "3"

services:
  db:
    image: "mysql:latest"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_HOST: "localhost"
      MYSQL_DATABASE: "open_weather"
      MYSQL_ROOT_PASSWORD: "password"
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - backend

  downloader:
    build:
      dockerfile: ./downloader.Dockerfile
    networks:
      - backend
    depends_on:
      - db

  service:
    build:
      dockerfile: ./service.Dockerfile
    depends_on:
      - downloader
    ports:
      - 8080:8080
    networks:
      - backend

  que:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672
    depends_on:
      - service
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend
    depends_on:
      - que

networks:
  backend:
    driver: bridge
