version: "3"

services:
  db:
    container_name: "MySQL"
    image: "mysql:latest"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: "open_weather"
      MYSQL_ROOT_PASSWORD: "password"
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - backend
    healthcheck:
      test:
        ["CMD", "mysqladmin", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  queue:
    container_name: "RabbitMQ"
    image: "rabbitmq:management"
    ports:
      - 15671:15671
      - 15672:15672
      - 15691:15691
      - 15692:15692
      - 25672:25672
      - 4369:4369
      - 5672:5672
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  downloader:
    container_name: "CRON"
    build:
      dockerfile: ./downloader.Dockerfile
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "Hello"]
      interval: 10s
      timeout: 5s
      retries: 3

  listener:
    container_name: "Listener"
    build:
      dockerfile: ./listener.Dockerfile
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
      downloader:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "Hello"]
      interval: 10s
      timeout: 5s
      retries: 3

  service:
    container_name: "REST_API"
    build:
      dockerfile: ./service.Dockerfile
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
      downloader:
        condition: service_healthy
      listener:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - backend
    healthcheck:
      test: ["CMD", "echo", "Hello"]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    container_name: "Adminer"
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:
    driver: bridge
